name: TextPay Test Automation
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      continue-on-error: true
      run: mvn clean test -DsuiteXmlFile=Textpay_Smoke.xml
      
    - name: Set current date
      id: set-date
      run: echo "::set-output name=today::$(date +'%Y-%m-%d')"
      shell: bash

    - name: Zip current test report
      id: zip-test
      run: |
        zip -r test-report-${{ steps.set-date.outputs.today }}.zip ./TestResults/${{ steps.set-date.outputs.today }}
      shell: bash
      
    - name: Upload Test Report
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: test-report-${{ steps.set-date.outputs.today }}.zip
